# Generated by Django 4.1.7 on 2023-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tutor_cod', models.CharField(db_column='tutor_cod', max_length=30, verbose_name='Código do tutor')),
                ('data_interdicao', models.DateField(db_column='data_interdicao', verbose_name='Data da interdição')),
                ('data_mandado', models.DateField(db_column='data_mandado', verbose_name='Data do mandado')),
                ('data_sentenca', models.DateField(db_column='data _sentenca', verbose_name='Data da sentença')),
                ('data_nascimento_interdicao', models.DateField(db_column='data_nascimento_interdicao', verbose_name='Data de nascimento')),
                ('num_processo', models.CharField(db_column='num_processo', max_length=60, verbose_name='Processo')),
                ('nome_juiz_mandado', models.CharField(db_column='nome_juiz_mandado', max_length=200, verbose_name='Nome do mandado')),
                ('nome_juiz_sentenca', models.CharField(db_column='nome_juiz_sentenca', max_length=200, verbose_name='Nome da sentença')),
                ('nome_interditado', models.CharField(db_column='nome_interditado', max_length=100, verbose_name='Nome')),
                ('nacionalidade_interditado', models.CharField(db_column='nacionalidade_interditado', max_length=50, verbose_name='Nacionalidade')),
                ('nome_pai_interditado', models.CharField(db_column='nome_pai_interditado', max_length=100, verbose_name='Nome do pai')),
                ('nome_mae_interditado', models.CharField(db_column='nome_mae_interditado', max_length=100, verbose_name='Nome da mãe')),
                ('endereco_interditado', models.CharField(db_column='endereco_interditado', max_length=100, verbose_name='Endereço')),
                ('bairro_interditado', models.CharField(db_column='bairro_interditado', max_length=40, verbose_name='Bairro')),
                ('cidade_interditado', models.CharField(db_column='cidade_interditado', max_length=30, verbose_name='Cidade')),
                ('cartorio_certidao_nascimento', models.CharField(db_column='cartorio_certidao_nascimento', max_length=150, verbose_name='Certidão de nascimento')),
                ('livro_certidao_nascimento', models.CharField(db_column='livro_certidao_nascimento', max_length=30, verbose_name='Livro de certidão de nascimento')),
                ('folha_certidao_nascimento', models.CharField(db_column='folha_certidao_nascimento', max_length=30, verbose_name='Folha da certidão de nascimento')),
                ('termo_certidao_nascimento', models.CharField(db_column='termo_certidao_nascimento', max_length=30, verbose_name='Termo da certidão de nascimento')),
                ('livro', models.CharField(db_column='livro', max_length=20, verbose_name='Livro')),
                ('folha', models.CharField(db_column='folha', max_length=20, verbose_name='Folha')),
                ('termo', models.CharField(db_column='termo', max_length=20, verbose_name='Termo')),
                ('observation', models.TextField(db_column='observation', max_length=80, verbose_name='Observação')),
                ('matricula', models.CharField(db_column='matricula', max_length=50, verbose_name='Matrícula')),
                ('cpfinterditado', models.CharField(db_column='cpfinterditado', max_length=50, verbose_name='CPF')),
            ],
        ),
    ]
