'''
Django serializers for vitin app.

Generated by 'kawe-henrique'
date_create: 16/02/2023

this serializer file has the function of converting complex data ( in our case the rest_framework and the models )
into native python data types that can be easily rendered in JSON, XML or other types of content.
'''

from rest_framework import serializers
from trabalho.models import Vitin


class vitinSerializers(serializers.ModelSerializer):
    '''
    A 'Serializer' of 'vitins', With function:
    * Serializer Data: Transform Object to Data.
    * Deserializer Data: Transform Data to Object.  
    '''

    class Meta:
        model = Vitin
        fields = "__all__"