'''
Django views for vitin app.

Generated by 'kawe-henrique'
date_create: 16/02/2023

this views file is where we put the 'logic' of our application.
It will extract information fom the model you create and deliver it to a template.
'''

from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import vitinSerializers
from .models import Vitin


class RequestTestAPI(APIView):
    '''View to check if API is Working'''

    def get(self, request, format=None):
        return Response({'API': 'OK'})

class VitincreateViewSet(generics.CreateAPIView):
    '''Create Product with Method: "POST"'''

    queryset = Vitin.objects.all()
    serializer_class = vitinSerializers

class VitinRetrieveUpdateDeleteViewSet(generics.RetrieveUpdateDestroyAPIView):
    '''Update/Delete/Retrieve Product with one these Method: "GET" / "UPDATE" / "DELETE"'''

    queryset = Vitin.objects.all()
    serializer_class = vitinSerializers

class VitinListViewSet(generics.ListAPIView):
    '''View to list all Product with Method: "GET"'''

    queryset = Vitin.objects.all()
    serializer_class = vitinSerializers